#! /usr/bin/env python

from coresyfDataCubeCreation import CoReSyFDataCubeCreation

if __name__ == '__main__':
    CoReSyFDataCubeCreation(__file__, 'CoReSyFDataCubeCreation.manifest.json').execute()
