#!/usr/bin/python2
import sys
sys.dont_write_bytecode = True

from coresyf_tiling import CoresyfTiling


if __name__ == '__main__':
    CoresyfTiling(__file__, 'CoresyfTiling.manifest.json').execute()
