#! /usr/bin/env python

from coresyf_data_cube_creation import CoReSyFDataCubeCreation

if __name__ == '__main__':
    CoReSyFDataCubeCreation(__file__, 'CoReSyFDataCubeCreation.manifest.json').execute()
